### ISSUE TITLE
[Bug] <Build Failled>

### ISSUE THREAD

**Issue by Minemetero** [XeContrast/FDPClientX-Reborn#13]
![image_2024-11-02_144609453](https://github.com/user-attachments/assets/ac0f05e2-a8e3-4638-832a-4e7ede32763d)

**Comment by Minemetero** [comment]
你这端完全不会用啊

**Comment by Minemetero** [comment]
包括菜单都唤醒不了

**Comment by Minemetero** [comment]
啥教程都没有

**Comment by XeContrast** [comment]
主播再他妈提脑残问题老子就要Block了

**Comment by Minemetero** [comment]
> 主播再他妈提脑残问题老子就要Block了

我操你妈的，怎么用你都不告诉我

**Comment by Minemetero** [comment]
什么版本啊

**Comment by XeContrast** [comment]
我操你妈的你自己有没有大脑偏要构建，你麻痹用jar会司马吗

**Comment by Minemetero** [comment]
。。。。。。。

**Comment by Minemetero** [comment]
从来没见过你这么文明的开发者

**Comment by XeContrast** [comment]
那你麻痹去用RavenXD，xiamc保证比我文明

**Comment by Minemetero** [comment]
你这个是Forge还是Fabric?

**Comment by XeContrast** [comment]
你麻痹见过1.8Fabric是吗，你妈的用Fabric-legacy写端是吗，你他妈有没有大脑

**Comment by Minemetero** [comment]
你他妈

**Comment by Minemetero** [comment]
你他妈这个ViaVersion只支持Fabric

**Comment by Minemetero** [comment]
还是只有1.10以前

**Comment by xia-mc** [comment]
提issue语气好点，维护者没有义务回答你的问题
